sudo: required

services:
  - docker


script:
  - docker-compose build

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-vuejs"
  env: "DockerVuejs-env"
  bucket_name: "elasticbeanstalk-us-east-1-245396819361"
  bucket_path: "docker-vuejs"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY