sudo: required

services:
  - docker


script:
  - docker-compose build

after_success:
  - docker build -t levantado/visitors-back ./backend
  - docker build -t levantado/visitors-revers ./revers_proxy
  - docker build -t levantado/visitors-frontend ./frontend
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  - docker push levantado/visitors-back
  - docker push levantado/visitors-revers
  - docker push levantado/visitors-frontend


#deploy:
    ##  provider: elasticbeanstalk
    ##  region: "us-east-1"
    ##  app: "docker-vuejs"
    ##  env: "DockerVuejs-env"
    ##  bucket_name: "elasticbeanstalk-us-east-1-245396819361"
    ##  bucket_path: "docker-vuejs"
    ##  on:
    ##    branch: master
    ##  access_key_id:
    ##    secure: $AWS_ACCESS_KEY
  ##  secret_access_key:
  ##    secure: $AWS_SECRET_KEY